project_id = "yftyxqnshmsstwkdceny"

[functions.send-lead-email]
verify_jwt = false

[functions.quiz-recommendation]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-insight-lead]
verify_jwt = false

[functions.generate-payment-report]
verify_jwt = false
